apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pitchfork.fullname" . }}
  labels:
    {{- include "pitchfork.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "pitchfork.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "pitchfork.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
            - containerPort: {{ .Values.service.healthCheckPort }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- toYaml .Values.service.env | nindent 12 }}
          resources:
            {{- toYaml .Values.service.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.service.livenessProbe.httpGet.path }}
              port: {{ .Values.service.healthCheckPort }}
            initialDelaySeconds: {{ .Values.service.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.service.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.service.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.service.readinessProbe.httpGet.path }}
              port: {{ .Values.service.healthCheckPort }}
            initialDelaySeconds: {{ .Values.service.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.service.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.service.readinessProbe.periodSeconds }}
          lifecycle:
            {{- toYaml .Values.service.lifecycle | nindent 12 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
